name = "YaoNoise"
uuid = "20bd9f5c-8432-5aa9-8b83-2dc4f2897bb9"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
